#ifndef TEATREE_CONFIG_H
#define TEATREE_CONFIG_H

#define EIGEN_ARRAYBASE_PLUGIN  "utils/eigen_addons.hpp"
#define EIGEN_MATRIXBASE_PLUGIN "utils/eigen_addons.hpp"

#cmakedefine TEATREE_BUILD_DATE "@TEATREE_BUILD_DATE@"

#cmakedefine TEATREE_VERSION_MAJOR @TEATREE_VERSION_MAJOR@

#cmakedefine TEATREE_VERSION_MINOR @TEATREE_VERSION_MINOR@

#cmakedefine TEATREE_VERSION "@TEATREE_VERSION@"

#cmakedefine TEATREE_ENABLE_OPENMP

#endif // TEATREE_CONFIG_H
